---
title: "p8105_hw1_jw3726"
author: "Jiabei Wang"
date: "2018年9月13日"
output: github_document

#```
#punif(10, min=0, max=5, lower.tail= TRUE, log.p= FALSE)
#```
```{r}
library(tidyverse)
example_df = tibble(
sample=runif(10, min=0, max=5),
logical = sample > 2,
vec_char = c("My", "name", "is", "Jiabei", "and", "I", "am", "a", "graduate", "student"), 
vec_factor = factor(c("male", "male", "male", "male", "male", "female", "female", "female", "female", "female")))
mean(example_df$sample)
mean(example_df$logical)
mean(example_df$vec_char)
mean(example_df$vec_factor)
as.numeric(example_df$logical)
as.numeric(example_df$vec_char)
as.numeric(example_df$vec_factor)
as.numeric(as.factor(example_df$vec_char))
as.numeric(as.character(example_df$vec_factor))




```
to calculate the mean, variable "sample" and "logical" work, since they are numeric. Varible "vec_char" and "vec_factor" don't work, since they are not numeric. 
when use "as. numeric"to logical, vec_char, and vec_factor, logical and vec_factor are converted to numeric numbers, while vec_char cannot be converted. 

```{r}
library(tidyverse)
example_df = tibble(
x = rnorm(1000),
y = rnorm(1000),
logical = x + y > 0)  
as.numeric(example_df$logical)
as.factor(example_df$logical)


```






```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

